name: My first GitHub action
on: [push]

jobs:
  build:
    runs-on: Ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8,3.9]
        
    steps:
    - uses: action/checkout@v3
    - name: Set Up Python
      uses: action/setup-python@v2
      with: 
        pyhton-version: ${{ matrix.python-version }}
        
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        
    - name: Run Tests
      run: |
        cd src
        python -m pytest addtion.py
